apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}
  labels:
    app: {{ .Values.appName }}
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: {{ .Values.appName }}
  selector:
    app: {{ .Values.appName }}
    tier: frontend
  type: NodePort
